course:
  course_id: 258284
  score:
    choice: 1
    matching: 2
    code: 5
    sorting: 1
    number: 3
    string: 3
    text: null

sections:
  # - title: Начало
  #   lessons:
  #     - title: Как всё начиналось
  #       steps: 1_start_of_events/10_history.yaml
  #     - title: Подготовка перед путешествием
  #       steps: 1_start_of_events/20_prepare.yaml
  #     - title: Продолжаем подготовку
  #       steps: 1_start_of_events/30_sequel_of_prepare.yaml
  # - title: Дело в прошлом
  #   lessons:
      # - title: Дело в прошлом
      #   steps: 2_last/10_how_started.yaml
      # - title: Новый знакомый
      #   steps: 2_last/20_new_person.yaml
      # - title: Продолжаем работу со светодиодами
      #   steps: 2_last/30_work_with_led.yaml
      # - title: Переменных требуют наши скетчи...
      #   steps: 2_last/40_variables.yaml
  - title: Внезапное происшествие
    lessons:
      # - title: Затишье перед бурей
      #   steps: 3_accident/10_still.yaml
      # - title: Внезапное происшествие
      #   steps: 3_accident/20_accident.yaml
      # - title: Зацикленные
      #   steps: 3_accident/30_cycles.yaml
      - title: Ожидание
        steps: 3_accident/40_waiting.yaml

  # - title: Динамика
  #   lessons:
      # - title: Законы динамики
      #   steps: dynamics/10_introduce.yaml
      # - title: Работа сил
      #   steps: dynamics/20_forses.yaml
      # - title: О колебательном движении
      #   steps: dynamics/30_oscillation.yaml
      # - title: Относительное движение точки
      #   steps: dynamics/40_relative_motion.yaml
      # - title: Динамика системы материальных точек
      #   steps: dynamics/50_system.yaml
      # - title: Дифференциальные уравнения движения системы
      #   steps: dynamics/60_drive_system.yaml
      # - title: Кинетическая энергия
      #   steps: dynamics/70_kinetic_energy.yaml
